//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class banco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public banco()
        {
            this.banco_financia_modelo = new HashSet<banco_financia_modelo>();
        }
    
        public byte id_banco { get; set; }
        public string nombre { get; set; }
        public Nullable<short> año_maximo_financiar { get; set; }
        public Nullable<decimal> valor_maximo_global { get; set; }
        public Nullable<int> km_maximo { get; set; }
        public Nullable<double> porcentaje_financiar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<banco_financia_modelo> banco_financia_modelo { get; set; }
    }
}
