//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class banco_financia_modelo
    {
        public string fk_modelo { get; set; }
        public byte fk_banco { get; set; }
        public decimal valor_limite { get; set; }
        public byte nivel_preferencia { get; set; }
    
        public virtual banco banco { get; set; }
        public virtual modelo modelo { get; set; }
    }
}
