//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comision
    {
        public int id_comision { get; set; }
        public byte porcentaje { get; set; }
        public System.DateTime fecha { get; set; }
        public int fk_usuario { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
