//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_gana_comision
    {
        public int fk_usuario { get; set; }
        public int fk_transaccion_venta { get; set; }
        public decimal monto { get; set; }
    
        public virtual transaccion_venta transaccion_venta { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
