//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehiculo()
        {
            this.vehiculo_tiene_costo = new HashSet<vehiculo_tiene_costo>();
            this.transaccion_compra = new HashSet<transaccion_compra>();
            this.transaccion_venta = new HashSet<transaccion_venta>();
        }
    
        public int id_vehiculo { get; set; }
        public short año { get; set; }
        public int kilometraje { get; set; }
        public string imagen { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public decimal valor_compra { get; set; }
        public Nullable<decimal> valor_venta { get; set; }
        public byte fk_vehiculo_estado { get; set; }
        public string fk_modelo { get; set; }
    
        public virtual modelo modelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehiculo_tiene_costo> vehiculo_tiene_costo { get; set; }
        public virtual vehiculo_estado vehiculo_estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaccion_compra> transaccion_compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaccion_venta> transaccion_venta { get; set; }
    }
}
